import {
  MAPS,
  distance,
  routeSegments,
  segmentDistance,
  onWater,
  inPolygon,
  type MapId,
  type MapDefinition,
  type Route,
} from './maps';

type Pairs = [number, number][];
interface Layout {
  region: MapId;
  name: string;
  paths: Pairs[];
  crossings?: number[];
  outline?: Pairs;
  reversed?: boolean;
  ruins?: Pairs;
}
// Each mission has authored paths. Later layouts split defensive coverage and
// bring independent entrances together progressively closer to the fortress.
const layouts: Layout[] = [
  {
    region: 'waldtal',
    name: 'Erste Wacht',
    outline: [
      [-15, -6],
      [-12, -9],
      [9, -9],
      [14, -5],
      [14, 8],
      [10, 10],
      [-10, 9],
      [-15, 5],
    ],
    paths: [
      [
        [-14, -5],
        [-9, -5],
        [-7, -3],
        [-7, 3],
        [-3, 3],
        [2, 3],
        [2, -3],
        [8, -3],
        [11, 0],
        [11, 6],
      ],
    ],
  },
  {
    region: 'waldtal',
    name: 'Am alten Tor',
    reversed: true,
    ruins: [
      [-6, 0],
      [-1, -1],
      [6, 7],
      [8, -7],
    ],
    paths: [
      [
        [-14, 0],
        [-10, 0],
        [-10, -6],
        [-4, -6],
        [-4, 5],
        [3, 5],
        [3, -4],
        [9, -4],
        [11, 0],
        [11, 6],
      ],
    ],
  },
  {
    region: 'waldtal',
    name: 'Belagerung im Tal',
    crossings: [-5, 5],
    outline: [
      [-15, -7],
      [-11, -10],
      [-4, -10],
      [0, -8],
      [5, -10],
      [12, -9],
      [15, -5],
      [14, 7],
      [10, 10],
      [3, 10],
      [0, 8],
      [-6, 10],
      [-12, 9],
      [-15, 6],
    ],
    paths: [
      [
        [-14, 0],
        [-11, 0],
        [-11, -6],
        [-6, -7],
        [-4, -5],
        [3, -5],
        [7, -7],
        [10, -4],
        [7, 0],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
      [
        [-14, 0],
        [-11, 0],
        [-11, 6],
        [-6, 7],
        [-4, 5],
        [3, 5],
        [5, 7],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
    ],
  },
  {
    region: 'silberfurt',
    name: 'An den Ufern',
    crossings: [-4, 4],
    paths: [
      [
        [-14, 0],
        [-10, 0],
        [-10, -5],
        [-6, -5],
        [-4, -4],
        [3, -4],
        [6, -6],
        [9, -4],
        [7, 0],
        [11, 0],
        [11, 6],
      ],
      [
        [-14, 0],
        [-10, 0],
        [-10, 5],
        [-6, 5],
        [-4, 4],
        [3, 4],
        [6, 6],
        [7, 0],
        [11, 0],
        [11, 6],
      ],
    ],
  },
  {
    region: 'silberfurt',
    name: 'Zwei Brücken',
    crossings: [-6, 6],
    paths: [
      [
        [-14, -2],
        [-11, -2],
        [-11, -7],
        [-6, -7],
        [-4, -6],
        [3, -6],
        [8, -6],
        [8, -2],
        [4, -2],
        [4, 2],
        [11, 2],
        [11, 6],
      ],
      [
        [-14, -2],
        [-11, -2],
        [-11, 6],
        [-7, 8],
        [-4, 6],
        [3, 6],
        [6, 7],
        [8, 4],
        [4, 2],
        [11, 2],
        [11, 6],
      ],
    ],
  },
  {
    region: 'silberfurt',
    name: 'Stromwacht',
    crossings: [-5, 5],
    paths: [
      [
        [-14, -7],
        [-10, -7],
        [-10, -2],
        [-6, -2],
        [-4, -5],
        [3, -5],
        [7, -7],
        [10, -4],
        [7, -1],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 1],
        [-6, 1],
        [-4, 5],
        [3, 5],
        [5, 8],
        [8, 7],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
    ],
  },
  {
    region: 'bernsteinhain',
    name: 'Goldene Pfade',
    paths: [
      [
        [-14, -6],
        [-10, -6],
        [-8, -8],
        [-3, -8],
        [-3, -3],
        [-6, 0],
        [0, 0],
        [3, -5],
        [8, -5],
        [8, 2],
        [11, 2],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-8, 8],
        [-3, 8],
        [-3, 3],
        [-6, 0],
        [0, 0],
        [3, -5],
        [8, -5],
        [8, 2],
        [11, 2],
        [11, 6],
      ],
    ],
  },
  {
    region: 'bernsteinhain',
    name: 'Die alten Ruinen',
    paths: [
      [
        [-14, -6],
        [-9, -6],
        [-9, -1],
        [-5, -1],
        [-5, -7],
        [2, -7],
        [2, -2],
        [6, -2],
        [6, 3],
        [11, 3],
        [11, 6],
      ],
      [
        [-14, 6],
        [-9, 6],
        [-9, 2],
        [-5, 2],
        [-5, 7],
        [2, 7],
        [2, 2],
        [6, -2],
        [6, 3],
        [11, 3],
        [11, 6],
      ],
    ],
  },
  {
    region: 'bernsteinhain',
    name: 'Zangenangriff',
    paths: [
      [
        [-14, -7],
        [-9, -7],
        [-9, -3],
        [-4, -3],
        [-4, -7],
        [3, -7],
        [3, -2],
        [7, 0],
        [7, 4],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 6],
        [-9, 6],
        [-9, 1],
        [-4, 1],
        [-4, 7],
        [2, 7],
        [2, 2],
        [7, 0],
        [7, 4],
        [11, 4],
        [11, 6],
      ],
      [
        [14, -7],
        [10, -7],
        [10, -3],
        [6, -3],
        [6, -7],
        [3, -7],
        [3, -2],
        [7, 0],
        [7, 4],
        [11, 4],
        [11, 6],
      ],
    ],
  },
  {
    region: 'frostklamm',
    name: 'Schneewacht',
    crossings: [-4, 4],
    paths: [
      [
        [-14, -7],
        [-10, -7],
        [-10, -2],
        [-6, -2],
        [-4, -4],
        [3, -4],
        [6, -6],
        [9, -4],
        [7, 0],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 1],
        [-6, 1],
        [-4, 4],
        [3, 4],
        [5, 7],
        [8, 7],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
      [
        [14, -7],
        [10, -7],
        [10, -9],
        [5, -9],
        [3, -6],
        [3, -4],
        [6, -6],
        [9, -4],
        [7, 0],
        [7, 3],
        [11, 3],
        [11, 6],
      ],
    ],
  },
  {
    region: 'frostklamm',
    name: 'Eisige Gabelung',
    crossings: [-6, 0, 6],
    paths: [
      [
        [-14, -5],
        [-10, -5],
        [-10, -8],
        [-6, -8],
        [-4, -6],
        [3, -6],
        [7, -7],
        [10, -5],
        [7, -2],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, -5],
        [-10, -5],
        [-10, 0],
        [-6, 0],
        [-6, -3],
        [-3, -3],
        [-3, 0],
        [3, 0],
        [5, 3],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 2],
        [-6, 2],
        [-4, 6],
        [3, 6],
        [5, 8],
        [8, 7],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
    ],
  },
  {
    region: 'frostklamm',
    name: 'Halt in der Klamm',
    crossings: [-6, 5],
    paths: [
      [
        [-14, -7],
        [-10, -7],
        [-10, -2],
        [-6, -2],
        [-4, -6],
        [3, -6],
        [6, -8],
        [10, -6],
        [8, -2],
        [8, 4],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 1],
        [-6, 1],
        [-4, 5],
        [3, 5],
        [5, 8],
        [8, 7],
        [8, 4],
        [11, 4],
        [11, 6],
      ],
      [
        [14, -7],
        [11, -7],
        [11, -3],
        [6, -3],
        [4, 0],
        [4, 3],
        [8, 4],
        [11, 4],
        [11, 6],
      ],
    ],
  },
  {
    region: 'glutspalten',
    name: 'Ascheregen',
    crossings: [-5, 0, 5],
    paths: [
      [
        [-14, 0],
        [-11, 0],
        [-11, -6],
        [-7, -7],
        [-4, -5],
        [3, -5],
        [6, -7],
        [10, -5],
        [8, -1],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 0],
        [-11, 0],
        [-8, -2],
        [-5, -2],
        [-5, 0],
        [3, 0],
        [5, 2],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 0],
        [-11, 0],
        [-11, 6],
        [-7, 8],
        [-4, 5],
        [3, 5],
        [5, 8],
        [8, 7],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
    ],
  },
  {
    region: 'glutspalten',
    name: 'Drei Feuerwege',
    crossings: [-6, 0, 6],
    paths: [
      [
        [-14, -7],
        [-10, -7],
        [-10, -3],
        [-6, -3],
        [-4, -6],
        [3, -6],
        [7, -8],
        [10, -5],
        [8, -2],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 0],
        [-11, 0],
        [-8, -1],
        [-6, 1],
        [-3, 1],
        [-3, 0],
        [3, 0],
        [5, -2],
        [8, -2],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 3],
        [-6, 3],
        [-4, 6],
        [3, 6],
        [5, 8],
        [8, 7],
        [7, 2],
        [5, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
    ],
  },
  {
    region: 'glutspalten',
    name: 'Die letzte Bastion',
    crossings: [-6, 0, 6],
    paths: [
      [
        [-14, -7],
        [-10, -7],
        [-10, -3],
        [-6, -3],
        [-4, -6],
        [3, -6],
        [5, -8],
        [8, -8],
        [8, -3],
        [6, 0],
        [9, 3],
        [7, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 0],
        [-11, 0],
        [-8, -1],
        [-6, 1],
        [-3, 1],
        [-3, 0],
        [3, 0],
        [5, -2],
        [6, 0],
        [9, 3],
        [7, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [-14, 6],
        [-10, 6],
        [-10, 3],
        [-6, 3],
        [-4, 6],
        [3, 6],
        [5, 8],
        [8, 8],
        [9, 5],
        [7, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
      [
        [14, -7],
        [11, -7],
        [11, -9],
        [6, -9],
        [4, -6],
        [7, -3],
        [10, -3],
        [10, 0],
        [7, 2],
        [9, 3],
        [7, 4],
        [7, 7],
        [11, 4],
        [11, 6],
      ],
    ],
  },
];

export const CAMPAIGN_MAPS: Record<string, MapDefinition> = Object.fromEntries(
  layouts.map((layout, i) => {
    const region = MAPS[layout.region];
    const routes: Route[] = layout.paths.map((pairs, n) => {
      const points = pairs.map(([x, z]) => ({ x, z }));
      return {
        id: n === 0 ? 'main' : `route-${n + 1}`,
        points,
        length: points.slice(1).reduce((sum, p, j) => sum + distance(p, points[j]), 0),
      };
    });
    const map: MapDefinition = {
      ...region,
      name: layout.name,
      outline: layout.outline?.map(([x, z]) => ({ x, z })) || region.outline,
      routes,
      waterways: layout.crossings
        ? [
            {
              points: [
                { x: 0, z: -11 },
                { x: 0, z: 11 },
              ],
              radius: i >= 12 ? 1.15 : 1,
              kind: i >= 12 ? 'lava' : 'water',
              waterfall: true,
            },
          ]
        : region.waterways,
      bridges: (layout.crossings || []).map((z) => ({
        a: { x: -2.2, z },
        b: { x: 2.2, z },
        width: 2.1,
        style: i >= 12 ? 'basalt' : i >= 9 ? 'stone' : 'wood',
      })),
      obstacles: [],
    };
    const segments = routeSegments(map);
    // Keep scenery clear of all paths and bridge approaches, including new branches.
    const candidates = [
      ...(layout.ruins || []).map(([x, z]) => ({ x, z, r: 1.1, kind: 'ruins' as const })),
      ...region.obstacles,
      ...Array.from({ length: 6 + i }, (_, n) => ({
        x: -11 + ((n * 7 + i * 3) % 23),
        z: -8 + ((n * 5 + i * 2) % 17),
        r: 0.65 + (n % 3) * 0.15,
        kind: (i >= 9 ? 'rocks' : i >= 6 ? 'ruins' : 'trees') as 'rocks' | 'ruins' | 'trees',
      })),
    ];
    map.obstacles = candidates.filter(
      (o, n) =>
        inPolygon(o, map.outline) &&
        !onWater(o, map, o.r + 0.4) &&
        distance(o, map.base) > o.r + 2.4 &&
        segments.every(({ a, b }) => segmentDistance(o, a, b) >= o.r + map.pathRadius + 0.3) &&
        !candidates.slice(0, n).some((other) => distance(o, other) < o.r + other.r),
    );
    // A different approach direction changes both the terrain and the fortress,
    // not merely the camera or the preview image.
    if (layout.reversed) {
      const turn = <T extends { x: number; z: number }>(p: T): T => ({ ...p, x: -p.x, z: -p.z });
      map.outline = map.outline.map(turn);
      map.base = turn(map.base);
      map.baseAngle += Math.PI;
      map.routes = map.routes.map((r) => ({ ...r, points: r.points.map(turn) }));
      map.waterways = map.waterways.map((w) => ({ ...w, points: w.points.map(turn) }));
      map.bridges = map.bridges.map((b) => ({ ...b, a: turn(b.a), b: turn(b.b) }));
      map.obstacles = map.obstacles.map(turn);
    }
    return [`mission-${String(i + 1).padStart(2, '0')}`, map];
  }),
);

/** Resolve the exact layout while retaining region IDs for saves and endless maps. */
export function battleMap(state: { mapId: MapId; ruleSet: string; missionId: string }): MapDefinition {
  return state.ruleSet === 'campaign' && CAMPAIGN_MAPS[state.missionId]
    ? CAMPAIGN_MAPS[state.missionId]
    : MAPS[state.mapId];
}
